### ISSUE TITLE
Another missing file：data/img_specific_questions.json

### ISSUE THREAD

**Issue by ranck626** [Haochen-Luo/CroPA#6]
Traceback (most recent call last):
  File "/data/codes/CroPA/inference.py", line 280, in <module>
    test(
  File "/data/codes/CroPA/inference.py", line 108, in test
    vqa_specific_instruction = load_img_specific_questions() 
  File "/data/codes/CroPA/utils/eval_tools.py", line 293, in load_img_specific_questions
    with open("data/img_specific_questions.json","r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/img_specific_questions.json'

**Comment by Haochen-Luo** [comment]
Hi,

I just uploaded the missing file
